In [1]:
%run C:/Users/HSS/dd.py
print('done')

done


In [2]:
pmf1 = np.array([[1, 2,  4, 2, 1],
                 [2, 4,  8, 4, 2],
                 [4, 8, 16, 8, 4],
                 [2, 4,  8, 4, 2],
                 [1, 2,  4, 2, 1]])
pmf1 = pmf1/pmf1.sum()

pmf1_marginal_x = np.round(pmf1.sum(axis=0), 2)
pmf1_marginal_y = np.round(pmf1.sum(axis=1), 2)


In [8]:
pmf1_marginal_x , pmf1_marginal_y[:, np.newaxis]

(array([0.1, 0.2, 0.4, 0.2, 0.1]), array([[0.1],
        [0.2],
        [0.4],
        [0.2],
        [0.1]]))

In [7]:
pmf1_marginal_x * pmf1_marginal_y[:, np.newaxis]

array([[0.01, 0.02, 0.04, 0.02, 0.01],
       [0.02, 0.04, 0.08, 0.04, 0.02],
       [0.04, 0.08, 0.16, 0.08, 0.04],
       [0.02, 0.04, 0.08, 0.04, 0.02],
       [0.01, 0.02, 0.04, 0.02, 0.01]])

In [ ]:
pmf1x = pmf1_marginal_x * pmf1_marginal_y[:, np.newaxis]

In [9]:
pmf1_marginal_y[:, np.newaxis].shape

(5, 1)

In [13]:
pmf1_marginal_y[:, np.newaxis]@(pmf1_marginal_x.reshape(1,5))

array([[0.01, 0.02, 0.04, 0.02, 0.01],
       [0.02, 0.04, 0.08, 0.04, 0.02],
       [0.04, 0.08, 0.16, 0.08, 0.04],
       [0.02, 0.04, 0.08, 0.04, 0.02],
       [0.01, 0.02, 0.04, 0.02, 0.01]])

In [14]:
pmf1_marginal_x.reshape(1,5)

array([[0.1, 0.2, 0.4, 0.2, 0.1]])

In [15]:
pmf1_marginal_x

array([0.1, 0.2, 0.4, 0.2, 0.1])